export const HomepageContentSection = () => {
  return (
    <section id="service-information" className="box-border caret-transparent pt-[70px] pb-0 md:pt-[120px] md:pb-0 bg-transparent">
      <div className="box-border caret-transparent max-w-[1200px] mx-auto px-[15px] md:px-[30px]">
        <div className="box-border caret-transparent mb-12 md:mb-16"><h2 className="text-white text-2xl font-bold box-border caret-transparent leading-[30px] mb-6 sm:text-3xl sm:leading-[38px] md:text-4xl md:leading-[43.2px]">Fencing, Tree Care & Landscaping</h2><p className="text-gray-200 text-base sm:text-lg md:text-xl box-border caret-transparent leading-7 mb-8">Cutting Edge helps customers across Perth, Dundee, Perthshire and nearby areas with the outdoor jobs that make properties safer, tidier and easier to enjoy. From new fences and old fence removal to hedge removal, turfing, patios, gravel and garden clearances, the team handles practical outdoor improvements with tidy workmanship. <a href="/contact" className="text-[#16a34a] hover:underline font-medium">Contact us to discuss your project</a>.</p></div>
        <div className="box-border caret-transparent mb-12 md:mb-16"><h2 className="text-white text-2xl font-bold box-border caret-transparent leading-[30px] mb-6 sm:text-3xl sm:leading-[38px] md:text-4xl md:leading-[43.2px]">Fencing Installation & Replacement</h2><p className="text-gray-200 text-base sm:text-lg md:text-xl box-border caret-transparent leading-7 mb-6">We install and replace wooden fencing, fence panels and tired boundary fencing for homes, gardens, farms and commercial spaces. Old fencing can be removed and disposed of, leaving your space neat and ready to use. <a href="/contact" className="text-[#16a34a] hover:underline font-medium">Ask for a fencing quote</a>.</p></div>
        <div className="box-border caret-transparent mb-12 md:mb-16"><h2 className="text-white text-2xl font-bold box-border caret-transparent leading-[30px] mb-6 sm:text-3xl sm:leading-[38px] md:text-4xl md:leading-[43.2px]">Garden Transformations</h2><p className="text-gray-200 text-base sm:text-lg md:text-xl box-border caret-transparent leading-7 mb-6">Whether your garden needs hedge removal, turfing, a patio, gravel areas or a full tidy-up, Cutting Edge can help turn neglected outdoor space into somewhere clean, practical and summer ready. <a href="/contact" className="text-[#16a34a] hover:underline font-medium">Make your garden summer ready</a>.</p></div>
        <div className="box-border caret-transparent mb-12 md:mb-16"><h2 className="text-white text-2xl font-bold box-border caret-transparent leading-[30px] mb-6 sm:text-3xl sm:leading-[38px] md:text-4xl md:leading-[43.2px]">Roof Cleaning & De-Mossing</h2><p className="text-gray-200 text-base sm:text-lg md:text-xl box-border caret-transparent leading-7 mb-6">Cutting Edge also provides hand-cleaned roof work, full de-mossing, gutter clearing and roof treatments. Removing moss and debris helps improve drainage, protect the roof and keep the property looking its best. <a href="/contact" className="text-[#16a34a] hover:underline font-medium">Get a free roof cleaning quote</a>.</p></div>
      </div>
    </section>
  );
};